# Generated by Django 3.2.5 on 2021-11-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usajob',
            name='promotion_potential',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usajob',
            name='security_clearance',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='usajob',
            name='security_clearance_required',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usajob',
            name='service_type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='usajob',
            name='vendor',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
