# Generated by Django 4.0.7 on 2022-10-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0001_initial'),
        ('job_grade', '0001_initial'),
        ('job_remuneration', '0001_initial'),
        ('job_offering_type', '0001_initial'),
        ('usa_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usajob',
            name='job_grades',
            field=models.ManyToManyField(related_name='%(data_name)s', to='job_grade.jobgrade'),
        ),
        migrations.AlterField(
            model_name='usajob',
            name='job_offering_types',
            field=models.ManyToManyField(related_name='%(data_name)s', to='job_offering_type.jobofferingtype'),
        ),
        migrations.AlterField(
            model_name='usajob',
            name='job_remunerations',
            field=models.ManyToManyField(related_name='%(data_name)s', to='job_remuneration.jobremuneration'),
        ),
        migrations.AlterField(
            model_name='usajob',
            name='job_schedules',
            field=models.ManyToManyField(related_name='%(data_name)s', to='job_schedule.jobschedule'),
        ),
    ]
