# Generated by Django 3.2.5 on 2021-12-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usa_job', '0002_auto_20211128_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usajob',
            options={'ordering': ['job_source__name', 'name'], 'verbose_name': 'usa job', 'verbose_name_plural': 'usa jobs'},
        ),
        migrations.RenameField(
            model_name='usajob',
            old_name='grades',
            new_name='job_grades',
        ),
        migrations.RenameField(
            model_name='usajob',
            old_name='offering_types',
            new_name='job_offering_types',
        ),
        migrations.RenameField(
            model_name='usajob',
            old_name='remunerations',
            new_name='job_remunerations',
        ),
        migrations.RenameField(
            model_name='usajob',
            old_name='schedules',
            new_name='job_schedules',
        ),
    ]
