# Generated by Django 3.2.5 on 2021-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobgrade',
            options={'ordering': ['code'], 'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
    ]
