# Generated by Django 3.2.5 on 2021-11-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_grade', '0002_alter_jobgrade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobgrade',
            options={'ordering': ['code'], 'verbose_name': 'job grade', 'verbose_name_plural': 'job grades'},
        ),
    ]
