# Generated by Django 4.0.1 on 2022-02-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferingType',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('code', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'job offering type',
                'verbose_name_plural': 'job offering types',
                'db_table': 'usa_jobs_job_offering_type',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
    ]
