# Generated by Django 3.2.5 on 2021-11-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferingType',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'job offering type',
                'verbose_name_plural': 'job offering types',
                'db_table': 'usa_jobs_job_offering_type',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
    ]
