# Generated by Django 3.2.5 on 2021-11-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offering_type', '0002_alter_jobofferingtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobofferingtype',
            options={'ordering': ['code'], 'verbose_name': 'job offering type', 'verbose_name_plural': 'job offering types'},
        ),
    ]
