# Generated by Django 3.2.10 on 2021-12-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offering_type', '0003_alter_jobofferingtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferingtype',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
