# Generated by Django 3.2.10 on 2021-12-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offering_type', '0004_alter_jobofferingtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferingtype',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
