# Generated by Django 3.2.5 on 2021-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_remuneration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobremuneration',
            options={'ordering': ['interval', '-max_range'], 'verbose_name': 'remuneration', 'verbose_name_plural': 'remunerations'},
        ),
    ]
