# Generated by Django 3.2.5 on 2021-11-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_remuneration', '0002_alter_jobremuneration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobremuneration',
            options={'ordering': ['interval', '-max_range'], 'verbose_name': 'job remuneration', 'verbose_name_plural': 'job remunerations'},
        ),
    ]
